### PR TITLE
Migrate docs to Docsify

### PR DESCRIPTION
**Pull request by captainsafia**
Docausaur got a little annoying after a while because customizing the look and feel took a lot of effort.

I wanted something that was clean and content-oriented and Docisfy seemed like a good fit. We can deploy it using GitHub pages or Zeit.

cc: @rgbkrk @willingc 

screen shot 2018-09-24 at 4 55 07 pm

screen shot 2018-09-24 at 4 55 10 pm

### CODE REVIEW

**Comment by captainsafia** [comment]
Outline for Content

- [ ] Landing page
- [ ] Getting started
      - [ ] Installation
      - [ ] Contributing
      - [ ] Things to know bebefore contributing
- [ ] Concepts
      - [ ] Jupyter Messaging Protocol and Kernels
      - [ ] The Notebook Format
      - [ ] Flow in nteract
- [ ] Building play.nteract.io from scratch
      - [ ] Setup and installation
      - [ ] Integrating the cell component
      - [ ] Integrating the output component
      - [ ] Communicating with the kernel

**Comment by rgbkrk** [comment]
This is fantastic to see, it's looking wonderful.

**Comment by rgbkrk** [comment]
Omg the docsify logo is toooooo cute.

My only apprehension with docsify after a quick glance is that we can't use our react components on the page. My thinking on that shouldn't block things though as the important work is the content and people should be able to iterate quickly together. 😄

**Comment by captainsafia** [comment]
> My only apprehension with docsify after a quick glance is that we can't use our react components on the page. My thinking on that shouldn't block things though as content is what matters.

From [our plans](https://paper.dropbox.com/doc/nteract-Component-Documentation-and-Unification--ANk9njaT9ih2JxUo1Va85vz6Ag-kEpZoLtzV0FCVpTD74O1Z), this repo will mostly store tutorials and conceptual documentation so I think we should be good on that front.

**Pull request merged**
