### PR TITLE
Add discussion parking doc

### PR DESCRIPTION
**Pull request by jdfreder**

### CODE REVIEW

**Comment by willingc** [comment]
As contributors, we value exploration, creativity, respectful collaboration, and a welcoming work environment. We formed the nteract organization to further these values. We, the nteract team,  encourage you to contribute as we explore interactive computing, application specs, tech, and designs.

**Comment by jdfreder** [comment]
^ ooo I like that!

**Comment by willingc** [comment]
Thought you might. Really it's just what you had flipped from passive voice to active ;-)

**Comment by jdfreder** [comment]
Do you want me to add that to the discussion.md file?  I opened this PR to dump some ephemeral chat data to somewhere that would persist.  All of the useful bits here, including your suggested phrasing, need a real home.  Until that home is found, discussion.md can hold them, and will persist much longer than Slack's chat history does.

**Comment by willingc** [comment]
Sure @jdfreder. I gift the words to you. Use them for good :smirk:

**Comment by rgbkrk** [comment]
> I gift the words to you. Use them for good :smirk:

Love that sentiment.

**Comment by betatim** [comment]
With great power comes great responsibility!

**Pull request merged**
